name: code_demonstration
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  injectable: ^2.5.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  build_runner: ^2.4.13
  slang: ^4.2.1
  localization: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.2
  auto_route: ^9.2.2
  flutter_svg: ^2.0.15
  flutter_gen: ^5.8.0
  injectable_generator: ^2.6.2
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  logger: ^2.5.0
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  rxdart: ^0.28.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/search/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 100
  integrations:
    flutter_svg: true

